[package]
rust-version.workspace = true
name = "hoki-launcher"
version = "0.1.0"
edition = "2021"
description = "App launcher for hoki watch"

[dependencies]
serde_json = { workspace = true }
shell-words = { workspace = true }
slint = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
