#ifndef SSC_CONFIG_H
#define SSC_CONFIG_H
#include "ssc_wire.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
struct ssc_config { uint64_t low,high; unsigned event,seen; size_t size; int error; unsigned char payload[4096]; };
static int sc_init(struct ssc_config *c,const unsigned char suid[18],unsigned event) {
 struct mt_field a,b;
 *c=(struct ssc_config){.event=event};
 if(mt_get(suid,18,1,1,&a)!=1 || mt_get(suid,18,2,1,&b)!=1)return -1;
 c->low=a.value;c->high=b.value;return 0;
}
static int sc_envelope(struct ssc_config *c,const unsigned char *p,size_t n) {
 struct mt_field source,a,b,event,id,ticks,payload;
 if(mt_get(p,n,1,2,&source)!=1 || mt_get(source.data,source.len,1,1,&a)!=1 || mt_get(source.data,source.len,2,1,&b)!=1)return -1;
 if(a.value!=c->low || b.value!=c->high)return 0;
 const unsigned char *end=p+n;int rc;
 while((rc=mt_next(&p,end,&event))>0)if(event.number==2) {
  if(event.wire!=2 || mt_get(event.data,event.len,1,5,&id)!=1 || mt_get(event.data,event.len,2,1,&ticks)!=1 || mt_get(event.data,event.len,3,2,&payload)!=1)return -1;
  if(id.value!=c->event)continue;
  if(c->seen || payload.len>sizeof c->payload)return -1;
  c->seen=1;c->size=payload.len;memcpy(c->payload,payload.data,payload.len);
 }
 return rc<0?-1:0;
}
static int sc_feed(struct ssc_config *c,unsigned message,const void *raw,size_t n) {
 if(c->error)return -1;
 if(message!=33 && message!=34)return 0;
 const unsigned char *p=raw;size_t pos=0;unsigned found=0;
 if(n>65536)goto bad;
 while(pos<n) {
  if(n-pos<3)goto bad;
  unsigned tag=p[pos],size=p[pos+1]|((unsigned)p[pos+2]<<8);pos+=3;
  if(size>n-pos)goto bad;
  if(tag==2 && (found++ || size<2 || (p[pos]|((unsigned)p[pos+1]<<8))!=size-2 || sc_envelope(c,p+pos+2,size-2)))goto bad;
  pos+=size;
 }
 if(found==1)return 0;
bad:c->error=1;return -1;
}
/* Identity strings are validated/generated by the caller; mode is a fixed CLI name.
 * Called after QMI release and successful journal finish, under the wake hold. */
static int sc_publish(const struct ssc_config *c,const char *directory,const char *boot,const char *session,const char *mode,const unsigned char suid[18]) {
 if(c->error || c->seen!=1){errno=EINVAL;return -1;}
 int dir=open(directory,O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOFOLLOW);if(dir<0)return -1;
 int fd=openat(dir,"config.pending",O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC|O_NOFOLLOW,0600);
 if(fd<0){close(dir);return -1;}
 FILE *f=fdopen(fd,"w");if(!f){close(fd);close(dir);return -1;}
 fprintf(f,"{\"version\":1,\"boot_id\":\"%s\",\"session_id\":\"%s\",\"mode\":\"%s\",\"event_id\":%u,\"source\":\"",boot,session,mode,c->event);
 for(unsigned i=0;i<18;i++)fprintf(f,"%02x",suid[i]);
 fputs("\",\"payload_hex\":\"",f);for(size_t i=0;i<c->size;i++)fprintf(f,"%02x",c->payload[i]);fputs("\"}\n",f);
 int error=ferror(f)?EIO:0;
 if(fflush(f) && !error)error=errno;
 if(!error && fsync(fd))error=errno;
 if(fclose(f) && !error)error=errno;
 if(!error && linkat(dir,"config.pending",dir,"config.json",0))error=errno;
 if(unlinkat(dir,"config.pending",0) && !error)error=errno;
 if(!error && fsync(dir))error=errno;
 close(dir);if(error){errno=error;return -1;}return 0;
}
#endif
