[package]
rust-version.workspace = true
name = "hoki-settings"
version = "0.1.0"
edition = "2021"
description = "Settings / quick access panel for hoki watch"

[dependencies]
serde_json = { workspace = true }
libc = { workspace = true }
slint = { workspace = true }
zbus = { workspace = true, features = ["blocking-api", "async-io"] }

[build-dependencies]
slint-build = { workspace = true }
