[package]
name = "hoki-wasm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.15", default-features = false, features = ["compat-1-2", "backend-winit", "renderer-software"] }
wasmi = "0.42"

[build-dependencies]
slint-build = "1.15"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
