panels=panel1
preferred_backend=LXQt:wlroots
iconTheme=hoki-desktop
[panel1]
plugins=mainmenu,quicklaunch,taskbar,worldclock
position=Bottom
desktop=0
panelSize=34
background-color=#eef1f5
font-color=#17202a
iconSize=24
length=100
reserveSpace=true
[mainmenu]
type=mainmenu
alignment=Left
showText=true
text=Start
menu_file=/opt/hoki-desktop/config/menus/hoki.menu
icon=/opt/hoki-desktop/share/icons/hoki-desktop/32/start-here-kde.svg
[quicklaunch]
type=quicklaunch
alignment=Left
apps\1\desktop=/opt/hoki-desktop/share/applications/hoki-desktop-foot.desktop
apps\2\desktop=/opt/hoki-desktop/share/applications/hoki-desktop-files.desktop
apps\size=2
[taskbar]
type=taskbar
buttonWidth=180
groupingEnabled=false
[worldclock]
type=worldclock
alignment=Right
