SUMMARY = "The friendly interactive shell"
HOMEPAGE = "https://fishshell.com"
LICENSE = "GPL-2.0-only & LGPL-2.0-or-later & MIT & PSF-2.0"
LIC_FILES_CHKSUM = "file://COPYING;md5=b7bced2729fdcb1cafe6c3eb569587a0"
SRC_URI = "git://github.com/fish-shell/fish-shell.git;protocol=https;nobranch=1 \
           git://github.com/fish-shell/rust-pcre2;protocol=https;nobranch=1;name=pcre2;destsuffix=pcre2"
SRCREV = "3478f78a0536414af623467c2addda4e9700a75d"
SRCREV_pcre2 = "85b7afba1a9d9bd445779800e5bcafeb732e4421"
SRCREV_FORMAT = "default_pcre2"

inherit cargo pkgconfig
require fish-crates.inc
DEPENDS += "pcre2 gettext-native"
# Embedded manual generation requires documentation tooling; normal shell,
# completions and localized messages remain enabled.
CARGO_BUILD_FLAGS += "--no-default-features --features localize-messages --bins -p fish"
export PREFIX = "${prefix}"
export BINDIR = "${bindir}"
export DATADIR = "${datadir}"
export SYSCONFDIR = "${sysconfdir}"
export FISH_BUILD_VERSION = "${PV}"
export PCRE2_SYS_STATIC = "0"

do_compile:prepend() {
    mkdir -p ${B}/target
}

do_install() {
    install -d ${D}${bindir} ${D}${datadir}/fish
    for command in fish fish_indent fish_key_reader; do
        install -m0755 ${B}/target/${CARGO_TARGET_SUBDIR}/$command ${D}${bindir}/$command
    done
    for entry in completions functions config.fish themes prompts; do
        cp -R ${S}/share/$entry ${D}${datadir}/fish/
    done
    sed -e 's|@extra_completionsdir@|${datadir}/fish/vendor_completions.d|g' \
        -e 's|@extra_functionsdir@|${datadir}/fish/vendor_functions.d|g' \
        -e 's|@extra_confdir@|${datadir}/fish/vendor_conf.d|g' \
        -e 's|@configure_input@|Generated by BitBake|g' \
        ${S}/share/__fish_build_paths.fish.in > ${D}${datadir}/fish/__fish_build_paths.fish
    install -d ${D}${sysconfdir}/fish/conf.d
}

pkg_postinst:${PN}() {
    touch $D${sysconfdir}/shells
    grep -qxF '${bindir}/fish' $D${sysconfdir}/shells || echo '${bindir}/fish' >> $D${sysconfdir}/shells
}
pkg_postrm:${PN}() {
    sed -i '\|^${bindir}/fish$|d' $D${sysconfdir}/shells
}
