[package]
rust-version.workspace = true
name = "hoki-spo2"
version = "0.1.0"
edition = "2021"
description = "SpO2 (blood oxygen) measurement app for Fossil Gen 6 (hoki) on AsteroidOS"

[dependencies]
libc = { workspace = true }
slint = { workspace = true }
zbus = { workspace = true, features = ["blocking-api"] }

[build-dependencies]
slint-build = { workspace = true }
