[package]
rust-version.workspace = true
name = "hoki-podcast"
version = "0.1.0"
edition = "2021"
description = "Podcast player for Fossil Gen 6 (hoki) on AsteroidOS"

[dependencies]
libc = { workspace = true }
slint = { workspace = true }
rss = { workspace = true }
ring = { workspace = true }
ureq = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rodio = { workspace = true, features = ["mp3"] }

[build-dependencies]
slint-build = { workspace = true }
