[package]
rust-version.workspace = true
name = "hoki-egui-demo"
version = "0.1.0"
edition = "2021"
description = "egui demo app for hoki watch (software-rendered)"

[dependencies]
egui = { workspace = true, features = ["default_fonts"] }
egui-winit = { workspace = true, features = ["wayland"] }
winit = { workspace = true, features = ["wayland", "rwh_06"] }
softbuffer = { workspace = true }
