[package]
rust-version.workspace = true
name = "hoki-music"
version = "0.1.1"
edition = "2021"

[features]
default = ["tls-system"]
tls-system = ["reqwest/native-tls"]
tls-rustcrypto = ["reqwest/rustls-tls-webpki-roots-no-provider", "dep:rustls", "dep:rustls-rustcrypto"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
symphonia = { workspace = true, features = ["mp3", "flac", "aac", "alac", "pcm", "vorbis", "ogg", "wav", "aiff", "isomp4", "id3v1", "id3v2", "opt-simd"] }
reqwest = { workspace = true, features = ["blocking", "json"] }
rustls = { workspace = true, optional = true, features = ["std", "tls12"] }
rustls-rustcrypto = { workspace = true, optional = true }
md5 = { workspace = true }
getrandom = { workspace = true }
libpulse-binding = { workspace = true }
libc = { workspace = true }
slint = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
