[System]
IconThemeName=hoki-desktop
FallbackIconThemeName=hicolor
Terminal=foot
[Desktop]
DesktopShortcuts=Home,Computer
WallpaperMode=color
BgColor=#183449
FgColor=#ffffff
Font="DejaVu Sans,10,-1,5,50,0,0,0,0,0"
[Volume]
MountOnStartup=false
MountRemovable=false
AutoRun=false
[Window]
LastWindowWidth=720
LastWindowHeight=420
RememberWindowSize=true
[FolderView]
BigIconSize=48
SmallIconSize=24
SidePaneIconSize=24
