[package]
name = "hoki-overlay"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
slint = { workspace = true }
wayland-client = { workspace = true }
wayland-protocols-wlr = { workspace = true, features = ["client"] }
libc = { workspace = true }
image = { workspace = true, features = ["png"] }

serde_json = { workspace = true }
zbus = { workspace = true, features = ["blocking-api", "async-io"] }

[build-dependencies]
slint-build = { workspace = true }
