[package]
rust-version.workspace = true
name = "hoki-connect"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Small native KDE Connect client for Hoki"

[dependencies]
libc = { workspace = true }
anyhow = { workspace = true }
openssl = { workspace = true, features = ["vendored"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
russh = { workspace = true }
tokio = { workspace = true, features = ["rt", "net", "process", "io-util", "sync", "time", "macros"] }
