#!/usr/bin/env python3
"""Add the fetched crates' declared license metadata to Cargo SBOM precursors.

The precursor, generated by the build itself, selects the crate set. Cargo
metadata supplies declarations for those exact package IDs; it never selects
extra workspace or target dependencies for the report.
"""

import argparse
import json
import subprocess
from pathlib import Path


def license_report(precursor, packages):
    graph = json.loads(precursor.read_text())
    if graph.get("version") != 1 or not isinstance(graph.get("crates"), list):
        raise ValueError(f"Unsupported Cargo SBOM precursor: {precursor}")
    crates = []
    for crate in graph["crates"]:
        package = packages.get(crate["id"])
        crates.append({
            "id": crate["id"],
            "name": package["name"] if package else None,
            "version": package["version"] if package else None,
            "source": package["source"] if package else None,
            "kind": crate["kind"],
            "features": crate["features"],
            "dependencies": crate["dependencies"],
            "licenseDeclared": package["license"] if package else None,
            "licenseFile": package["license_file"] if package else None,
            "repository": package["repository"] if package else None,
        })
    return {
        "schemaVersion": 1,
        "artifact": precursor.name.removesuffix(".cargo-sbom.json"),
        "root": graph["root"],
        "rustc": graph.get("rustc", {}).get("version"),
        "crates": crates,
        "needsReview": [i for i, crate in enumerate(crates)
                        if not crate["licenseDeclared"] and not crate["licenseFile"]],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--precursors", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    result = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--frozen", "--offline",
         "--manifest-path", str(args.manifest)],
        check=True, capture_output=True, text=True,
    )
    packages = {package["id"]: package for package in json.loads(result.stdout)["packages"]}
    precursors = sorted(args.precursors.glob("*.cargo-sbom.json"))
    if not precursors:
        raise SystemExit(f"No Cargo SBOM precursors in {args.precursors}")
    args.output.mkdir(parents=True, exist_ok=True)
    for precursor in precursors:
        report = license_report(precursor, packages)
        destination = args.output / (report["artifact"] + ".licenses.json")
        destination.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
        print(f"{destination.name}: {len(report['crates'])} crates, "
              f"{len(report['needsReview'])} need license review")


if __name__ == "__main__":
    main()
