#!/usr/bin/env python3
"""Generate locked BitBake inputs for the layer's locally maintained Rust sources."""
import argparse
from pathlib import Path
import tomllib
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]


def generate(projects, workspace=False):
    uris, crates, git = [], {}, {}
    lockfiles = [ROOT / 'projects/Cargo.lock'] if workspace else []
    if workspace:
        uris += ['file://Cargo.toml;subdir=projects', 'file://Cargo.lock;subdir=projects']
    for project in sorted(set(projects)):
        base = ROOT / 'projects' / project
        for name in ('Cargo.toml', 'Cargo.lock', 'build.rs', 'src', 'tests', 'ui', 'deploy', 'opk', 'assets', 'fonts'):
            if workspace and name == 'Cargo.lock':
                continue
            if (base / name).exists():
                uris.append(f'file://{project}/{name};subdir=projects')
        for path in sorted(base.glob('*.png')):
            uris.append(f'file://{project}/{path.name};subdir=projects')
        extra_inputs = []
        if project == 'hoki-health-recorder':
            extra_inputs = [base / name for name in ('README.md', 'CAPABILITIES.md')]
            extra_inputs += sorted((base / 'ssc').glob('*.h'))
            extra_inputs += [base / 'ssc/collector.c']
        elif project == 'hoki-activity':
            extra_inputs = [base / name for name in ('daemon.py', 'activity.py', 'export.py', 'README.md')]
            for name in ('health_client.py', 'power_client.py'):
                uris.append(f'file://hoki-health-recorder/deploy/{name};subdir=projects')
        elif project == 'ble-ssh/watch-rs':
            uris.append('file://ble-ssh/shared;subdir=projects')
            extra_inputs = [base / name for name in ('ble-ssh-watch.service', 'ble-ssh-watch.env', 'com.ble_ssh.conf')]
        for path in extra_inputs:
            if not path.is_file():
                raise ValueError(f'Missing input: {path}')
            uris.append(f'file://{project}/{path.relative_to(base)};subdir=projects')
        if not workspace:
            lockfiles.append(base / 'Cargo.lock')
    for lockfile in lockfiles:
        for package in tomllib.loads(lockfile.read_text())['package']:
            source = package.get('source', '')
            if source.startswith('registry+'):
                if source != 'registry+https://github.com/rust-lang/crates.io-index':
                    raise ValueError(f'Unsupported registry: {source}')
                key = (package['name'], package['version'])
                checksum = package['checksum']
                if key in crates and crates[key] != checksum:
                    raise ValueError(f'Conflicting checksums: {key}')
                crates[key] = checksum
            elif source.startswith('git+'):
                git[package['name']] = source
            elif source:
                raise ValueError(f'Unsupported dependency: {source}')
    uris.append('file://shared;subdir=projects')
    extra = []
    for name, source in sorted(git.items()):
        parsed = urlsplit(source[4:])
        # cargo_common patches repository dependencies to these local crate paths.
        dest = 'git-deps/' + name
        # Fetch into repository root; cargo patch path adjusted for nested crates below.
        # BlueR generates identifiers from its pinned Bluetooth database submodule.
        scheme = 'gitsm' if name == 'bluer' else 'git'
        uris.append(f'{scheme}://{parsed.netloc}{parsed.path};protocol={parsed.scheme};nobranch=1;name={name};destsuffix={dest}')
        extra.append(f'SRCREV_{name} = "{parsed.fragment}"')
    if git:
        extra.append('SRCREV_FORMAT = "' + '_'.join(sorted(git)) + '"')
    for name, version in sorted(crates):
        uris.append(f'crate://crates.io/{name}/{version}')
    lines = ['# Generated by tools/update-runtime-recipes.py; do not edit.', 'SRC_URI += " \\']
    lines += ['    ' + uri + ' \\' for uri in uris]
    lines += ['"', *extra]
    lines += [f'SRC_URI[{name}-{version}.sha256sum] = "{checksum}"' for (name, version), checksum in sorted(crates.items())]
    return '\n'.join(lines) + '\n'


def outputs():
    projects = [line.split('|')[0] for line in (ROOT / 'runtime-projects.txt').read_text().splitlines() if line and not line.startswith('#')]
    return {
        'recipes-hoki/hoki-ui/hoki-sources.inc': generate(projects, workspace=True),
        'recipes-hoki/hoki-health-recorder/health-sources.inc': generate(['hoki-health-recorder']),
        'recipes-connectivity/ble-ssh/ble-sources.inc': generate(['ble-ssh/watch-rs']),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.write_text(content)
    if stale:
        raise SystemExit('Regenerate runtime recipe inputs: ' + ', '.join(stale))

if __name__ == '__main__':
    main()
