[package]
rust-version.workspace = true
name = "hoki-audiobook"
version = "0.1.0"
edition = "2021"
description = "Audiobook player for AsteroidOS"

[dependencies]
zbus = { workspace = true, features = ["blocking-api", "async-io"] }
libc = { workspace = true }
slint = { workspace = true }
gstreamer = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }

[build-dependencies]
slint-build = { workspace = true }
