[package]
rust-version.workspace = true
name = "hoki-watchface"
version = "0.1.0"
edition = "2021"
description = "Minimal clock watchface for hoki watch"

[dependencies]
slint = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }
shell-words = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
